name: Comunicador de la Legion

on:
  workflow_dispatch:
    inputs:
      villano:
        description: 'Nombre del villano que envia el mensaje'
        required: true
        type: choice
        options:
          - 'Dr. Maligno'
          - 'El Profesor'
          - 'El Cientifico Loco'
          - 'El Maestro del Caos'
        default: 'Dr. Maligno'
      mensaje:
        description: 'Contenido del mensaje'
        required: true
        type: string
        default: 'Mensaje secreto de la Legion'
      prioridad:
        description: 'Prioridad del mensaje'
        required: true
        type: choice
        options:
          - 'Alta'
          - 'Media'
          - 'Baja'
        default: 'Media'
      cow_character:
        description: 'Tipo de mensaje'
        required: true
        type: choice
        options:
          - 'C3PO'
          - 'atat'
          - 'bees'
          - 'clippy'
        default: 'Media'

jobs:
  transmitir-mensaje:
    runs-on: ubuntu-latest

    steps:
      - name: Instalar dependencias 📦
        run: sudo apt-get install -y cowsay

      - name: Imprimir inputs
        run: |
          echo "================================"
          echo "  Transmision interceptada      "
          echo "================================"
          echo ""
          echo "De: ${{ inputs.villano }}"
          echo ""
          echo "Fecha $(date -u +"%d/%m/%y %H:%M UTC")"
          echo ""
          echo "--- Mensaje ---"
          cowsay -f ${{ inputs.cow_character }} "${{ inputs.mensaje }}"
          echo ""
          echo "--- ${{ inputs.villano }}"
          echo "..."
